// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVTAN5w8U2TM8RJhHny23Aay7klLKeSkk',
    appId: '1:722722967168:web:ee02ef30544650fcc82065',
    messagingSenderId: '722722967168',
    projectId: 'shigoto-ca5a6',
    authDomain: 'shigoto-ca5a6.firebaseapp.com',
    storageBucket: 'shigoto-ca5a6.firebasestorage.app',
    measurementId: 'G-HSJW40LEED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0979zdk6HNoW1E3OaX6Ib6fJQ89ITvRU',
    appId: '1:722722967168:android:efd5cfe54a4c0800c82065',
    messagingSenderId: '722722967168',
    projectId: 'shigoto-ca5a6',
    storageBucket: 'shigoto-ca5a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHUwXe-2-aWdp-SbC676L4KxG5NVnIV4I',
    appId: '1:722722967168:ios:f9a23bc236c70a3ec82065',
    messagingSenderId: '722722967168',
    projectId: 'shigoto-ca5a6',
    storageBucket: 'shigoto-ca5a6.firebasestorage.app',
    androidClientId: '722722967168-rk2c4ro102p4o4glmc9hisq46ml5ebak.apps.googleusercontent.com',
    iosClientId: '722722967168-k9qmj74h9ajktt6907bpmup4mdeiogve.apps.googleusercontent.com',
    iosBundleId: 'com.example.shigoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHUwXe-2-aWdp-SbC676L4KxG5NVnIV4I',
    appId: '1:722722967168:ios:f9a23bc236c70a3ec82065',
    messagingSenderId: '722722967168',
    projectId: 'shigoto-ca5a6',
    storageBucket: 'shigoto-ca5a6.firebasestorage.app',
    androidClientId: '722722967168-rk2c4ro102p4o4glmc9hisq46ml5ebak.apps.googleusercontent.com',
    iosClientId: '722722967168-k9qmj74h9ajktt6907bpmup4mdeiogve.apps.googleusercontent.com',
    iosBundleId: 'com.example.shigoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVTAN5w8U2TM8RJhHny23Aay7klLKeSkk',
    appId: '1:722722967168:web:5998c26197d564f3c82065',
    messagingSenderId: '722722967168',
    projectId: 'shigoto-ca5a6',
    authDomain: 'shigoto-ca5a6.firebaseapp.com',
    storageBucket: 'shigoto-ca5a6.firebasestorage.app',
    measurementId: 'G-20BB11BND3',
  );
}
